services:
  - type: web
    name: property-listing-system
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb://mongo:FAoaZTesCRotGIjSDQOiHCtNSsQumkvO@metro.proxy.rlwy.net:19845
      - key: REDIS_URL
        fromService:
          type: redis
          name: property-listing-system
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3000
      - key: RATE_LIMIT_WINDOW
        value: "15"
      - key: RATE_LIMIT_MAX_REQUESTS
        value: "100"

  - type: redis
    name: property-listing-system
    ipAllowList: []
    plan: free

databases:
  - name: property-listing-mongodb
    databaseName: property-listing
    plan: free
    ipAllowList: [] 